cxx_library(
    name = "add_service",
    srcs = glob(["*.cpp"]),
    exported_headers = glob(["*.h"]),
    exported_deps = [
        "//add_service/if:if-cpp",
    ],
    compiler_flags = [
      "-std=c++20",
    ],
    visibility = ["PUBLIC"],
)
